name: CI - Main Branch

# Trigger workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Define a job to test and build the backend
  test-and-build-backend:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for GitHub Actions

    steps:
      - name: Checkout code # Step to get the code from your repository
        uses: actions/checkout@v2

      - name: Setup Python environment # Set up a Python environment for backend tests
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify the Python version

      - name: Install dependencies # Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run backend tests # Run tests on the backend code
        run: python -m unittest discover -s tests

  # Define a job to build and push Docker images
  build-and-push-images:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    needs: test-and-build-backend # Ensure this job only runs after successful backend tests

    steps:
      - name: Checkout code # Get the code from your repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub # Log in to Docker Hub to push images
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub username from GitHub secrets
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Docker Hub password from GitHub secrets

      - name: Build and push backend image # Build and push the backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Current directory
          file: backend.dockerfile # Path to backend Dockerfile
          push: true # Push image to Docker Hub
          tags: username/webcounter-backend:${{ github.sha }} # Tag image with commit SHA

      - name: Build and push frontend image #Build and push the frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Current directory
          file: frontend.dockerfile # Path to frontend Dockerfile
          push: true # Push image to Docker Hub
          tags: username/webcounter-frontend:${{ github.sha }} # Tag image with commit SHA
